spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/remote_classroom}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:$Hubh@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=ap-south-1
aws.bucketName=remote-classroom-videos-02
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
gemini.api.key=${GEMINI_API_KEY}
openai.api.key=${OPENAI_API_KEY}
AGORA_APP_ID=284b4a9de4eb4f8fb6f81666304ee762
AGORA_APP_CERTIFICATE=080eedb6ba7b4275806659fb8aa4fc11
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey123}
jwt.expiration=86400000

# Connection Pooling
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000